### ISSUE TITLE
Feature: User can search for teams

### ISSUE THREAD

**Issue by Tarekchaaban** [Tarekchaaban/Fifapedia#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to pull up any international or club team from a team name search.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to input a team name into the search bar and click submit.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![f1 desktop](https://user-images.githubusercontent.com/113570457/210003980-dbded47a-8412-43ea-a4b1-f1e27154cead.png)

![f1 mobile](https://user-images.githubusercontent.com/113570457/210003986-8ee0a313-828c-41f7-a242-e9d87af0a8fd.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` with a GET request function to the API server requesting information on a specific team using the input provided by the user in the search bar when submit is clicked.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for html skeleton and header.
- [x] Create a team search component with a search bar and a button that has a submit handler for the search form.
- [x] Create fifa logo footer component (only visible on search view) 
- [x] Create a single-team-details view component that utilizes the servers response from your get request to populate the teams logo and information on the team, as well as the teams stadium picture and some information on the stadium.

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
