### ISSUE TITLE
Feature: User can log out

### ISSUE THREAD

**Issue by Tarekchaaban** [Tarekchaaban/Fifapedia#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can log out of their account
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will navigate to the menu icon, click on it, and then click on the sign out button.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![f10 mobile](https://user-images.githubusercontent.com/113570457/210005585-00a6cd88-f0de-47c9-b592-f2ac17e63762.png)
![f10 desktop](https://user-images.githubusercontent.com/113570457/210005586-a1d09647-799c-42aa-9312-f35d3bc0af39.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to ...
- [x] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
