### ISSUE TITLE
Feature: User can create a watchlist for teams.

### ISSUE THREAD

**Issue by Tarekchaaban** [Tarekchaaban/Fifapedia#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to add teams to a watchlist in order to keep track of them.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click on the add team button and this will add it to the list.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![f2 mobile](https://user-images.githubusercontent.com/113570457/210004259-0ae532ce-c31d-4ea9-91c9-ee5e02e3ec5c.png)
![f2 desktop](https://user-images.githubusercontent.com/113570457/210004267-8d1d0fc5-ae19-4798-96d7-d8ad6f71af31.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` with the provided code from the Database website to create the tables for the team (and users? wont be used until feature 8 but are needed for UserId as teams uses it as a foreign key.)

### ☁️ Server Tasks

- [x] Update `server/index.js` to receive the post request to update the database by creating the sql insert statement, making a db query, then responding to the client.
- [x] Update server/index.js to receive the get request and retrieve the team tables info by creating a sql select statement, making a db query, then responding back to the client.
- [x] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Add an 'Add Team' button to your teamsearch component that allows the user to add the team they've searched up to a watch list.
- [x] Create addTeamHandler function within your component that will be associated with a click event listener on the Add Team button. Utilize a post request to update your database with the currently selected team when the user presses Add Team.
- [x] Create a Teamlist component that will display all teams that have been added to the database. 
- [x] Create a get request on your teamlist component to communicate with the server and retrieve all the teams that have been added to the teams table.
- [x] Complete the necessary html and css for the button, and the new teamlist component.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
