### ISSUE TITLE
Feature: User can delete teams from watchlist.

### ISSUE THREAD

**Issue by Tarekchaaban** [Tarekchaaban/Fifapedia#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to remove teams from their watchlist they no longer wish to keep track of.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click on the x button to remove the team from watchlist. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![f3 desktop](https://user-images.githubusercontent.com/113570457/210004402-612f44f4-fe66-45eb-bbf1-5a8aec20ffa6.png)
![f3 mobile](https://user-images.githubusercontent.com/113570457/210004410-cc055529-089d-47e4-9ada-a2e2ed6f50ba.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to handle the delete fetch request by creating an sql delete statement, querying the database, and responding to the client with the data to allow this.state.teamlist to update.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Use an x symbol from font awesome and place it in the right hand corner of your individual list item divs.
- [x] Create a modal that will pop up when the user clicks on the x.
- [x] Create buttons on the modal that either confirm the deletion, or cancel it.
- [x] Create a clickHandler function for your x to open the modal, for your Cancel button in the modal to cancel the deletion, and your confirm button to confirm deletion.
- [x] Create a fetch request in your confirm clickhandler in your team list component with the method delete. Parameter will be the event.target closest div key which correlates with the teamId.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
