### ISSUE TITLE
Feature: User can view list of players from team.

### ISSUE THREAD

**Issue by Tarekchaaban** [Tarekchaaban/Fifapedia#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view all the players from a specified team and season.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click on a team from their watchlist, then input a season they wish to see and the players will render on the page. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![f5 desktop](https://user-images.githubusercontent.com/113570457/210004742-3296e97b-3074-4e46-b651-817a0c300db3.png)
![f5 mobile](https://user-images.githubusercontent.com/113570457/210004746-51596aa8-8028-489e-92c6-5c2dbaade6c0.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to handle the fetch get request with the appropriate headers and respond to the client with the data.
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update TeamList component to have a new event listener method on any list item that changes this.props.view to 'players' to hide TeamList component, and show new Players component. As well as store the teamId from the id attribute on the list item in a new state currentTeamId.
- [x] Create a Players component that has another form with a dropdown input where the user can select a season for the team, and create a fetch get request using the search parameters of the stored teamId as well as the newly input season number.
- [x] Store current team name and current team logo photourl in state and pass it to the Players component as a prop for use.
- [x] Use the servers response from the API and create a player list, similar to your team list. 

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
