### ISSUE TITLE
Feature: User can view individual player stats.

### ISSUE THREAD

**Issue by Tarekchaaban** [Tarekchaaban/Fifapedia#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view more specific stats on one player.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will click on a specific player after choosing the season and loading all the players from the team.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![f6 desktop](https://user-images.githubusercontent.com/113570457/210004937-f0cf0ffe-4aaf-4241-ae84-e30aae7262ed.png)
![f6 mobile](https://user-images.githubusercontent.com/113570457/210004941-273f6d43-6ec9-48a8-83f2-5fb27600f265.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [ ] Update `server/index.js` to handle the get request and send it to the API. Respond to the client with the data received.
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create an click event listener in your player component on one of the player cards that changes the view to 'single player'  and stores the clicked players name in a new state called currentPlayerName. 
- [ ] Create a fetch request to the server using the stored teamId, season, and player name. Use the response to create a single player card in the new SinglePlayer Component.

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
